---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-cat-producer
spec:
  selector:
    matchLabels:
      app: kafka-cat-producer
  template:
    metadata:
      labels:
        app: kafka-cat-producer
    spec:
      containers:
        - name: kafka-cat-producer
          image: confluentinc/cp-kafkacat
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "while true; do  echo -e 'send kafka message '`date`'\r\n'|kafkacat -P  -b my-release-kafka.kafka.svc.cluster.local:9092 -t test; echo 'send message to kafka'; sleep $((1 + RANDOM % 11)); done"]
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-cat-consumer
spec:
  selector:
    matchLabels:
      app: kafka-cat-consumer
  template:
    metadata:
      labels:
        app: kafka-cat-consumer
    spec:
      containers:
        - name: kafka-cat-consumer
          image: confluentinc/cp-kafkacat
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "kafkacat -C -b my-release-kafka.kafka.svc.cluster.local:9092 -t test"]
---
kind: Service
apiVersion: v1
metadata:
  name: service-kafka-cat-consumer
  namespace: default
spec:
  selector:
    app: kafka-cat-consumer
  type: ExternalName
  externalName: my-release-kafka.kafka.svc.cluster.local
